# Generated by Django 4.2.1 on 2023-06-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pexmfdt',
            new_name='pexpdt',
        ),
    ]
